/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface BuddhiliveSelect {
    'blname': string;
    'bltitle': string;
    'colorTheme': string;
    'filterOptions': (elemnts: any, ev: any) => Promise<void>;
    'getValue': () => Promise<string>;
    'selectedItem': (elements: any, ev: any) => Promise<void>;
    'setOptions': (data: any) => Promise<void>;
    'setValues': (values: any) => Promise<void>;
    'toggleDropdown': (elemnts: any, ev: any) => Promise<void>;
  }
}

declare global {


  interface HTMLBuddhiliveSelectElement extends Components.BuddhiliveSelect, HTMLStencilElement {}
  var HTMLBuddhiliveSelectElement: {
    prototype: HTMLBuddhiliveSelectElement;
    new (): HTMLBuddhiliveSelectElement;
  };
  interface HTMLElementTagNameMap {
    'buddhilive-select': HTMLBuddhiliveSelectElement;
  }
}

declare namespace LocalJSX {
  interface BuddhiliveSelect {
    'blname'?: string;
    'bltitle'?: string;
    'colorTheme'?: string;
  }

  interface IntrinsicElements {
    'buddhilive-select': BuddhiliveSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'buddhilive-select': LocalJSX.BuddhiliveSelect & JSXBase.HTMLAttributes<HTMLBuddhiliveSelectElement>;
    }
  }
}


